
# prefix: /admin/lot

app_admin_lot_index:
    path:     /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: app_admin_lot_list, permanent: true }

app_admin_lot_list:
    path:     /list
    defaults: { _controller: App\Controller\Admin\LotController:listAction }

app_admin_lot_view:
    path:     /{id}
    defaults: { _controller: App\Controller\Admin\LotController:viewAction }
    requirements:
        id: '\d+'

app_admin_lot_view_bets:
    path:     /{id}/bets
    defaults: { _controller: App\Controller\Admin\LotController:viewBetsAction }
    requirements:
        id: '\d+'
