
# prefix: /admin/profile

app_admin_profile_index:
    path:     /
    defaults: { _controller: App\Controller\Admin\ProfileController:indexAction }

app_admin_profile_edit:
    path:     /
    defaults: { _controller: App\Controller\Admin\ProfileController:editAction }

app_admin_profile_auth_log:
    path:     /auth-log
    defaults: { _controller: App\Controller\Admin\ProfileController:authLogAction }

app_admin_profile_change_username:
    path:     /change-username
    defaults: { _controller: App\Controller\Admin\ProfileController:changeUsernameAction }

app_admin_profile_change_password:
    path:     /change-password
    defaults: { _controller: App\Controller\Admin\ProfileController:changePasswordAction }

app_admin_profile_change_email:
    path:     /change-email
    defaults: { _controller: App\Controller\Admin\ProfileController:changeEmailAction }
