
services:

# Validators
    app.symfony.validator.exist:
        class: App\Symfony\Validator\Constraints\EntityExistsValidator
        arguments:
            - '@doctrine'
        tags:
            - { name: validator.constraint_validator, alias: validator.exist }

    app.symfony.validator.user_password:
        class: App\Symfony\Validator\Constraints\UserPasswordValidator
        arguments:
            - '@security.token_storage'
            - '@security.encoder_factory'
        tags:
            - { name: validator.constraint_validator, alias: validator.user_password }

# Exception Controller
    app.twig.controller.exception:
        class: App\Controller\ExceptionController
        parent: twig.controller.exception

# Assets
    app.symfony.assets.version_strategy.last_modified:
        class: PTS\SymfonyAsset\LastModifyStrategy
        arguments:
            - '%kernel.project_dir%/public'

# Security
    app.symfony.security.authentication.success_handler.ajax:
        class: App\Symfony\Security\Authentication\AjaxAuthenticationSuccessHandler
        parent: security.authentication.success_handler

    app.symfony.security.authentication.failure_handler.ajax:
        class: App\Symfony\Security\Authentication\AjaxAuthenticationFailureHandler
        parent: security.authentication.failure_handler
        arguments:
            - '@translator'

# Form
    app.symfony.form.helper:
        class: App\Symfony\Form\FormHelper

    app.symfony.form.extension.novalidate:
        class: App\Symfony\Form\Extension\NovalidateFormTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }
