
services:

# Validators
    app.symfony.validator.exist:
        class: App\Symfony\Validator\Constraints\EntityExistsValidator
        arguments:
            - '@doctrine'
        tags:
            - { name: validator.constraint_validator, alias: validator.exist }

    app.symfony.validator.user_password:
        class: App\Symfony\Validator\Constraints\UserPasswordValidator
        arguments:
            - '@security.token_storage'
            - '@security.encoder_factory'
        tags:
            - { name: validator.constraint_validator, alias: validator.user_password }


# Exception Controller
    app.twig.controller.exception:
        class: App\Controller\ExceptionController
        parent: twig.controller.exception
