
# prefix: /admin

app_admin_default_index:
    path:     /
    defaults: { _controller: App\Controller\Admin\DefaultController:indexAction }

# Profile
app_admin_profile:
    prefix:   /profile
    resource: 'admin/profile.yaml'

# Users
app_admin_user:
    prefix:   /user
    resource: 'admin/user.yaml'

# User review
app_admin_user_review:
    prefix:   /user/review
    resource: 'admin/user_review.yaml'

# Auth log
app_admin_auth_log:
    prefix:   /auth-log
    resource: 'admin/auth_log.yaml'
