
# prefix: /private

app_private_default_index:
    path:     /
    defaults: { _controller: App\Controller\PrivateArea\DefaultController:indexAction }

# Profile
app_private_profile:
    prefix:   /profile
    resource: 'private/profile.yaml'

# User
app_private_user:
    prefix:   /user
    resource: 'private/user.yaml'

# User review
app_private_user_review:
    prefix:   /user/review
    resource: 'private/user_review.yaml'

# Chats
app_private_chat:
    prefix:   /chat
    resource: 'private/chat.yaml'

# Chat messages
app_private_chat_message:
    prefix:   /chat/message
    resource: 'private/chat_message.yaml'
