
app:
    resource: '@AppBundle/Resources/config/routing.yml'

# FOSJsRoutingBundle
fos_js_routing:
    resource: '@FOSJsRoutingBundle/Resources/config/routing/routing.xml'

# GregwarCaptchaBundle
gregwar_captcha_routing:
    resource: '@GregwarCaptchaBundle/Resources/config/routing/routing.yml'
