app:
    resource: '@AppBundle/Controller/'
    type: annotation

# FOSJsRoutingBundle
fos_js_routing:
    resource: '@FOSJsRoutingBundle/Resources/config/routing/routing.xml'

# GregwarCaptchaBundle
gregwar_captcha_routing:
    resource: '@GregwarCaptchaBundle/Resources/config/routing/routing.yml'
