
# prefix: /private/profile

app_private_profile_index:
    path:     /
    defaults: { _controller: App\Controller\PrivateArea\ProfileController:indexAction }

app_private_profile_auth_log:
    path:     /auth-log
    defaults: { _controller: App\Controller\PrivateArea\ProfileController:authLogAction }

app_private_profile_change_username:
    path:     /change-username
    defaults: { _controller: App\Controller\PrivateArea\ProfileController:changeUsernameAction }

app_private_profile_change_password:
    path:     /change-password
    defaults: { _controller: App\Controller\PrivateArea\ProfileController:changePasswordAction }

app_private_profile_change_email:
    path:     /change-email
    defaults: { _controller: App\Controller\PrivateArea\ProfileController:changeEmailAction }

app_private_profile_change_timezone:
    path:     /change-timezone
    defaults: { _controller: App\Controller\PrivateArea\ProfileController:changeTimezoneAction }

app_private_profile_oauth:
    path:     /oauth
    defaults: { _controller: App\Controller\PrivateArea\ProfileController:oauthAction }

app_private_profile_oauth_disconnect:
    path:     /oauth/{service}/disconnect
    defaults: { _controller: App\Controller\PrivateArea\ProfileController:oauthDisconnectAction }
