
# prefix: /private

app_private_default_index:
    path:     /
    defaults: { _controller: AppBundle:PrivateArea/Default:index }

# Profile
app_private_profile:
    prefix:   /profile
    resource: 'private/profile.yml'
