
# prefix: /admin

app_admin_default_index:
    path:     /
    defaults: { _controller: App\Controller\Admin\DefaultController:indexAction }

# Profile
app_admin_profile:
    prefix:   /profile
    resource: 'admin/profile.yml'

# Users
app_admin_user:
    prefix:   /user
    resource: 'admin/user.yml'

# User review
app_admin_user_review:
    prefix:   /user/review
    resource: 'admin/user_review.yml'

# Auth log
app_admin_auth_log:
    prefix:   /auth-log
    resource: 'admin/auth_log.yml'

# Lot
app_admin_lot:
    prefix:   /lot
    resource: 'admin/lot.yml'

# Lot bet
app_admin_lot_bet:
    prefix:   /lot
    resource: 'admin/lot_bet.yml'
