
# prefix: /private

app_private_default_index:
    path:     /
    defaults: { _controller: App\Controller\PrivateArea\DefaultController:indexAction }

# Profile
app_private_profile:
    prefix:   /profile
    resource: 'private/profile.yml'

# User
app_private_user:
    prefix:   /user
    resource: 'private/user.yml'

# User review
app_private_user_review:
    prefix:   /user/review
    resource: 'private/user_review.yml'

# Chats
app_private_chat:
    prefix:   /chat
    resource: 'private/chat.yml'

# Chat messages
app_private_chat_message:
    prefix:   /chat/message
    resource: 'private/chat_message.yml'

# Lot
app_private_lot:
    prefix:   /lot
    resource: 'private/lot.yml'

# Lot bet
app_private_lot_bet:
    prefix:   /lot/bet
    resource: 'private/lot_bet.yml'
