
# prefix: /private

app_private_default_index:
    path:     /
    defaults: { _controller: App\Controller\PrivateArea\DefaultController:indexAction }

# Profile
app_private_profile:
    prefix:   /profile
    resource: 'private/profile.yml'

# User
app_private_user:
    prefix:   /user
    resource: 'private/user.yml'

# Chats
app_private_chat:
    prefix:   /chat
    resource: 'private/chat.yml'

# Chat messages
app_private_chat_message:
    prefix:   /chat/message
    resource: 'private/chat_message.yml'
