imports:
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi: ~
    translator: { fallbacks: ['%env(APP_LOCALE)%'] }
    secret: '%env(APP_SECRET)%'
    router:
        resource: '%kernel.project_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%env(APP_LOCALE)%'
    trusted_hosts: ~
    session:
        handler_id: snc_redis.session.handler
    fragments: ~
    http_method_override: true
    assets:
        version_strategy: app.symfony.assets.version_strategy.last_modified
    php_errors:
        log: true
    cache:
        pools:
            #app и system зарезервированны и очень мутные в плане настройки
            cache.default: #кеш общего пользования
                adapter:  cache.adapter.redis
                provider: snc_redis.default
                public:   true
                #namespace: '' # https://github.com/symfony/symfony/pull/26743
            cache.validator:
                adapter:  cache.adapter.redis
                provider: snc_redis.system
                public:   false
            cache.serializer:
                adapter:  cache.adapter.redis
                provider: snc_redis.system
                public:   false
            cache.annotations:
                adapter:  cache.adapter.redis
                provider: snc_redis.system
                public:   false
            cache.twig:
                adapter:  cache.adapter.redis
                provider: snc_redis.system
                public:   true #обязательно true для TwigCacheBundle
            cache.doctrine_metadata:
                adapter:  cache.adapter.redis
                provider: snc_redis.system
                public:   false
            cache.doctrine_query:
                adapter:  cache.adapter.redis
                provider: snc_redis.system
                public:   false
            cache.doctrine_result:
                adapter:  cache.adapter.redis
                provider: snc_redis.system
                public:   false
            cache.doctrine_second_level:
                adapter:  cache.adapter.redis
                provider: snc_redis.system
                public:   false

# Twig Configuration
twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'form_theme/hint_help.html.twig'
    exception_controller: app.twig.controller.exception:showAction

# TwigCacheBundle
twig_cache:
    service: cache.twig

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%env(DATABASE_HOST)%'
        port: '%env(DATABASE_PORT)%'
        dbname: '%env(DATABASE_NAME)%'
        user: '%env(DATABASE_USER)%'
        password: '%env(DATABASE_PASSWORD)%'
        charset: UTF8
        wrapper_class: App\Doctrine\DBAL\ReopeningConnectionWrapper
        types:
            json:       App\Doctrine\DBAL\Types\JsonType
            datetimetz: App\Doctrine\DBAL\Types\DateTimeTzType

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type:      annotation
                dir:       '%kernel.source_dir%/Entity'
                prefix:    'App\Entity\'
                alias:     App
        default_repository_class: App\Doctrine\ORM\EntityRepository
        dql:
            string_functions:
                field: DoctrineExtensions\Query\Mysql\Field
        metadata_cache_driver:
            type: service
            id:   doctrine_cache.providers.doctrine_metadata
        query_cache_driver:
            type: service
            id:   doctrine_cache.providers.doctrine_query
        result_cache_driver:
            type: service
            id:   doctrine_cache.providers.doctrine_result
        second_level_cache:
            region_cache_driver:
                type: service
                id:   doctrine_cache.providers.doctrine_second_level
            enabled: true

# Doctrine Cache (только для кеширования доктрины)
doctrine_cache:
    custom_providers:
        psr6:
            prototype:        app.doctrine.cache.provider.psr6
            definition_class: App\Doctrine\Cache\Provider\Definition\Psr6Definition
        psr16:
            prototype:        app.doctrine.cache.provider.psr16
            definition_class: App\Doctrine\Cache\Provider\Definition\Psr16Definition
    providers:
        doctrine_metadata:
            custom_provider:
                type: psr6
                options:
                    cache_pool: cache.doctrine_metadata
        doctrine_query:
            custom_provider:
                type: psr6
                options:
                    cache_pool: cache.doctrine_query
        doctrine_result:
            custom_provider:
                type: psr6
                options:
                    cache_pool: cache.doctrine_result
        doctrine_second_level:
            custom_provider:
                type: psr6
                options:
                    cache_pool: cache.doctrine_second_level

# Чистка APC cache
accelerator_cache:
    host: '%env(HOST_MAIN)%'
    web_dir: '%kernel.project_dir%/public'

# Doctrine Migrations
doctrine_migrations:
    dir_name:        '%kernel.source_dir%/Migration'
    namespace:       App\Migration
    table_name:      migration
    custom_template: '%kernel.source_dir%/Doctrine/DBAL/Migrations/template'

# Gregwar Captcha
gregwar_captcha:
    as_url:           true
    reload:           true
    font:             '%kernel.project_dir%/vendor/gregwar/captcha/Font/captcha2.ttf'
    quality:          90
    max_front_lines:  2
    max_behind_lines: 2
    disabled:         '%kernel.debug%'

# Recaptcha
ewz_recaptcha:
    public_key:  '%env(RECAPTCHA_KEY_PUBLIC)%'
    private_key: '%env(RECAPTCHA_KEY_PRIVATE)%'
    locale_key:  '%kernel.default_locale%'
    enabled:     '%kernel.not_debug%'
    ajax:        false

# Redis
snc_redis:
    clients:
        default:
            type:    phpredis
            alias:   default
            dsn:     '%env(REDIS_DSN)%'
            logging: '%kernel.debug%'
        system:
            type:    phpredis
            alias:   system
            dsn:     "%env(REDIS_DSN)%/1"
            logging: "%kernel.debug%"
        session:
            type:    phpredis
            alias:   session
            dsn:     "%env(REDIS_DSN)%/2"
            logging: "%kernel.debug%"
    session:
        client: session

# Swiftmailer Configuration
swiftmailer:
    default_mailer: default
    mailers:
        default:
            transport: 'mail'
#            host:      '%env(SWIFTMAILER_DEFAULT_HOST)%'
#            username:  '%env(SWIFTMAILER_DEFAULT_USER)%'
#            password:  '%env(SWIFTMAILER_DEFAULT_PASSWORD)%'
#           spool: #не забываем  вызывать swiftmailer:spool:send #пока отключаем spool чтобы сразу происходила отправка
#               type: memory #это не работает в винде
#               type: file
        monolog:
            transport: 'mail'
#            transport: '%env(SWIFTMAILER_MONOLOG_TRANSPORT)%'
#            host:      '%env(SWIFTMAILER_MONOLOG_HOST)%'
#            username:  '%env(SWIFTMAILER_MONOLOG_USER)%'
#            password:  '%env(SWIFTMAILER_MONOLOG_PASSWORD)%'

# FOS JsRouting Bundle #todo
#fos_js_routing:

# Chebur Search
chebur_search:
    param_names:
        page:  page
        limit: limit
        sort:  sort
        order: order
    services:
        manager: app.chebur.search.manager
    templates:
        pagination: '@CheburSearch/Pagination/bs4beta.html.twig'
        limitation: '@CheburSearch/Limitation/bs4beta.html.twig'
        sorting:    '@CheburSearch/Sorting/bs4beta.html.twig'

# OAuth
hwi_oauth:
    http:
        client: csa_guzzle.client.hwi_oauth.psr7
        message_factory: app.guzzle.message_factory
    firewall_names:        [main]
    use_referer:           true #todo один большой из-за полной неразберихи в урлах и редиректах
    target_path_parameter: return_url
    connect:
        confirmation:      false
        account_connector: app.oauth.connector
    resource_owners:
        vkontakte: # App\OAuth\ResourceOwnerHelper::VKONTAKTE_NAME
            type:          vkontakte
            client_id:     '%env(OAUTH_VKONTAKTE_CLIENT_ID)%'
            client_secret: '%env(OAUTH_VKONTAKTE_CLIENT_SECRET)%'
            scope:         'email'

csa_guzzle: # https://github.com/csarrazi/CsaGuzzleBundle
    profiler: '%kernel.debug%'
    clients:
        hwi_oauth:
