imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ru

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        handler_id: snc_redis.session.handler
    fragments: ~
    http_method_override: true
    assets:
        version_strategy: app.symfony.assets.version_strategy.last_modified
    php_errors:
        log: true
    cache:
        pools:
            #app и system зарезервированны и очень мутные в плане настройки
            cache.default: #кеш общего пользования
                adapter:  cache.adapter.redis
                provider: snc_redis.default
                public:   true
                #namespace: '' # https://github.com/symfony/symfony/pull/26743
            cache.validator:
                adapter:  cache.adapter.redis
                provider: snc_redis.system
                public:   false
            cache.serializer:
                adapter:  cache.adapter.redis
                provider: snc_redis.system
                public:   false
            cache.annotations:
                adapter:  cache.adapter.redis
                provider: snc_redis.system
                public:   false
            cache.twig:
                adapter:  cache.adapter.redis
                provider: snc_redis.system
                public:   true #обязательно true для TwigCacheBundle
            cache.doctrine_metadata:
                adapter:  cache.adapter.redis
                provider: snc_redis.system
                public:   false
            cache.doctrine_query:
                adapter:  cache.adapter.redis
                provider: snc_redis.system
                public:   false
            cache.doctrine_result:
                adapter:  cache.adapter.redis
                provider: snc_redis.system
                public:   false
            cache.doctrine_second_level:
                adapter:  cache.adapter.redis
                provider: snc_redis.system
                public:   false

# Twig Configuration
twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'form_theme/hint_help.html.twig'
    exception_controller: app.twig.controller.exception:showAction

# TwigCacheBundle
twig_cache:
    service: cache.twig

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        wrapper_class: App\Doctrine\DBAL\ReopeningConnectionWrapper
        types:
            json_array: App\Doctrine\DBAL\Types\JsonArrayType
            datetimetz: App\Doctrine\DBAL\Types\DateTimeTzType

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type:      annotation
                dir:       '%kernel.source_dir%/Entity'
                prefix:    'App\Entity\'
                alias:     App
        default_repository_class: App\Doctrine\ORM\EntityRepository
        dql:
            string_functions:
                field: DoctrineExtensions\Query\Mysql\Field
        metadata_cache_driver:
            type: service
            id:   doctrine_cache.providers.doctrine_metadata
        query_cache_driver:
            type: service
            id:   doctrine_cache.providers.doctrine_query
        result_cache_driver:
            type: service
            id:   doctrine_cache.providers.doctrine_result
        second_level_cache:
            region_cache_driver:
                type: service
                id:   doctrine_cache.providers.doctrine_second_level
            enabled: true

# Doctrine Cache (только для кеширования доктрины)
doctrine_cache:
    custom_providers:
        psr6:
            prototype:        app.doctrine.cache.provider.psr6
            definition_class: App\Doctrine\Cache\Provider\Definition\Psr6Definition
        psr16:
            prototype:        app.doctrine.cache.provider.psr16
            definition_class: App\Doctrine\Cache\Provider\Definition\Psr16Definition
    providers:
        doctrine_metadata:
            custom_provider:
                type: psr6
                options:
                    cache_pool: cache.doctrine_metadata
        doctrine_query:
            custom_provider:
                type: psr6
                options:
                    cache_pool: cache.doctrine_query
        doctrine_result:
            custom_provider:
                type: psr6
                options:
                    cache_pool: cache.doctrine_result
        doctrine_second_level:
            custom_provider:
                type: psr6
                options:
                    cache_pool: cache.doctrine_second_level

# Чистка APC cache
accelerator_cache:
    host: '%host.main%'
    web_dir: '%kernel.project_dir%/public'

# Doctrine Migrations
doctrine_migrations:
    dir_name:        '%kernel.source_dir%/Migration'
    namespace:       App\Migration
    table_name:      migration
    custom_template: '%kernel.source_dir%/Doctrine/DBAL/Migrations/template'

# Gregwar Captcha
gregwar_captcha:
    as_url:           true
    reload:           true
    font:             '%kernel.project_dir%/vendor/gregwar/captcha/Font/captcha2.ttf'
    quality:          90
    max_front_lines:  2
    max_behind_lines: 2
    disabled:         '%kernel.debug%'

# Recaptcha
ewz_recaptcha:
    public_key:  '%recaptcha.public_key%'
    private_key: '%recaptcha.private_key%'
    locale_key:  '%kernel.default_locale%'
    enabled:     '%kernel.not_debug%'
    ajax:        false

# Redis
snc_redis:
    clients:
        default:
            type:    phpredis
            alias:   default
            dsn:     '%redis.dsn%'
            logging: '%kernel.debug%'
        system:
            type:    phpredis
            alias:   system
            dsn:     "%redis.dsn%/1"
            logging: "%kernel.debug%"
        session:
            type:    phpredis
            alias:   session
            dsn:     "%redis.dsn%/2"
            logging: "%kernel.debug%"
    session:
        client: session

# Swiftmailer Configuration
swiftmailer:
    default_mailer: default
    mailers:
        default:
            transport: '%swiftmailer.default.transport%'
            host:      '%swiftmailer.default.host%'
            username:  '%swiftmailer.default.user%'
            password:  '%swiftmailer.default.password%'
#           spool: #не забываем  вызывать swiftmailer:spool:send #пока отключаем spool чтобы сразу происходила отправка
#               type: memory #это не работает в винде
#               type: file
        monolog:
            transport: '%swiftmailer.monolog.transport%'
            host:      '%swiftmailer.monolog.host%'
            username:  '%swiftmailer.monolog.user%'
            password:  '%swiftmailer.monolog.password%'

# FOS JsRouting Bundle #todo
#fos_js_routing:

# Chebur Search
chebur_search:
    param_names:
        page:  page
        limit: limit
        sort:  sort
        order: order
    services:
        manager: app.chebur.search.manager
    templates:
        pagination: '@CheburSearch/Pagination/bs4beta.html.twig'
        limitation: '@CheburSearch/Limitation/bs4beta.html.twig'
        sorting:    '@CheburSearch/Sorting/bs4beta.html.twig'

# php-http httplug
httplug:
    clients:
        default:
            factory: 'httplug.factory.curl'
        guzzle:
            factory: 'httplug.factory.guzzle6'
        socket:
            factory: 'httplug.factory.socket'

# OAuth
hwi_oauth:
    firewall_names:        [main]
    use_referer:           true #todo один большой из-за полной неразберихи в урлах и редиректах
    target_path_parameter: return_url
    connect:
        confirmation:      false
        account_connector: app.oauth.connector
    resource_owners:
        vkontakte: # App\OAuth\ResourceOwnerHelper::VKONTAKTE_NAME
            type:          vkontakte
            client_id:     '%oauth.vkontakte.client_id%'
            client_secret: '%oauth.vkontakte.client_secret%'
            scope:         'email'

# FOS Rest
fos_rest: # http://symfony.com/doc/master/bundles/FOSRestBundle/configuration-reference.html
    # disable_csrf_role: #todo разобраться что за зверь
    # access_denied_listener: #todo https://symfony.com/doc/master/bundles/FOSRestBundle/3-listener-support.html#security-exception-listener
    # unauthorized_challenge: #todo https://symfony.com/doc/master/bundles/FOSRestBundle/3-listener-support.html#security-exception-listener
    param_fetcher_listener: false #http://symfony.com/doc/master/bundles/FOSRestBundle/param_fetcher_listener.html
    # cache_dir:
    # allowed_methods_listener: #todo https://symfony.com/doc/master/bundles/FOSRestBundle/3-listener-support.html#allowed-http-methods-listener
    # routing_loader: #todo https://symfony.com/doc/current/bundles/FOSRestBundle/5-automatic-route-generation_single-restful-controller.html

    body_converter:         false #ParamConverter преобразования тела в объект http://symfony.com/doc/master/bundles/FOSRestBundle/request_body_converter_listener.html
    # service:
    # serializer:
    view: #todo почитать ещё подробнее
        formats:
            json: true
            xml:  false
        templating_formats: #рендерингом html этот бандл заниматься не будет !
            html: false
        force_redirects:
            html: false
        #view_response_listener: make 'return View' possible #todo http://symfony.com/doc/master/bundles/FOSRestBundle/view_response_listener.html
    #todo exception:        http://symfony.com/doc/master/bundles/FOSRestBundle/4-exception-controller-support.html
    body_listener:          false #возможность в теле передавать json в случае например POST http://symfony.com/doc/master/bundles/FOSRestBundle/body_listener.html
    #todo format_listener:  https://symfony.com/doc/master/bundles/FOSRestBundle/format_listener.html
    versioning:             false #todo only by query http://symfony.com/doc/master/bundles/FOSRestBundle/versioning.html
    zone:
        - { path: ^/api/* }

# Api doc
nelmio_api_doc:

    documentation: #todo OMG https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md
        host: api.example.com
        schemes: [http, https]
        info:
            title: Swagger Sample App
            description: This is a sample server Petstore server.
            termsOfService: http://swagger.io/terms/
            contact:
                name: API Support
                url: http://www.swagger.io/support
                email: support@swagger.io
            license:
                name: Apache 2.0
                url: http://www.apache.org/licenses/LICENSE-2.0.html
            version: 1.0.1
        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Value: Bearer {jwt}'
                name: Authorization
                in: header
        security:
            - Bearer: []

    models:
        use_jms: false
    areas:
        default:
            path_patterns:
                - ^/api(?!/doc/$)
            # host_patterns:

