imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ru

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: app.twig.controller.exception:showAction

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        wrapper_class: App\Doctrine\DBAL\ReopeningConnectionWrapper
        types:
            json_array: App\Doctrine\DBAL\Types\JsonArrayType

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        default_repository_class: App\Doctrine\ORM\EntityRepository

# Doctrine Migrations
doctrine_migrations:
    dir_name:   '%kernel.project_dir%/src/App/Migration'
    namespace:  App\Migration
    table_name: migration

# Gregwar Captcha
gregwar_captcha:
    as_url:           true
    reload:           true
    font:             '%kernel.root_dir%/../vendor/gregwar/captcha/Font/captcha2.ttf'
    quality:          90
    max_front_lines:  2
    max_behind_lines: 2
    disabled:         '%kernel.debug%'

# Recaptcha
ewz_recaptcha:
    public_key:  '%recaptcha.public_key%'
    private_key: '%recaptcha.private_key%'
    locale_key:  '%kernel.default_locale%'
    enabled:     '%kernel.not_debug%'
    ajax:        false

# Redis
snc_redis:
    #todo sessions, doctrine, firewall
    clients:
        default:
            type:    predis
            alias:   default
            dsn:     '%redis.dsn%'
            logging: '%kernel.debug%'

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
#    spool: #не забываем  вызывать swiftmailer:spool:send #пока отключаем spool чтобы сразу происходила отправка
#        type: memory #это не работает в винде
#        type: file

# Chebur Search
chebur_search:
    param_names:
        page:  page
        limit: limit
        sort:  sort
        order: order
    services:
        manager: app.chebur.search.manager
    templates:
        pagination: '@CheburSearch/Pagination/bs4beta.html.twig'
        limitation: '@CheburSearch/Limitation/bs4beta.html.twig'
        sorting:    '@CheburSearch/Sorting/bs4beta.html.twig'
