
# Общедоступные пути
app_public:
    resource: 'routes/public.yaml'


# Все что связано с авторизацией, регистрацией, сбросом пароля
app_auth:
    resource: 'routes/auth.yaml'


# Только для авторизованных пользователей
app_private:
    prefix:   /private
    resource: 'routes/private.yaml'


# Админка
app_admin:
    prefix:   /admin
    resource: 'routes/admin.yaml'


# FOSJsRoutingBundle
fos_js_routing:
    resource: '@FOSJsRoutingBundle/Resources/config/routing/routing.xml'

# GregwarCaptchaBundle
gregwar_captcha_routing:
    resource: '@GregwarCaptchaBundle/Resources/config/routing/routing.yml'

# HWIOAuthBundle
hwi_oauth_routing:
    resource: 'routes/oauth.yaml'
