
# Общедоступные пути
app_public:
    resource: 'routing/public.yml'


# Все что связано с авторизацией, регистрацией, сбросом пароля
app_auth:
    resource: 'routing/auth.yml'


# Только для авторизованных пользователей
app_private:
    prefix:   /private
    resource: 'routing/private.yml'


# Админка
app_admin:
    prefix:   /admin
    resource: 'routing/admin.yml'


# API
app_api:
    prefix:   /api
    resource: 'routing/api.yml'


# FOSJsRoutingBundle
fos_js_routing:
    resource: '@FOSJsRoutingBundle/Resources/config/routing/routing.xml'

# GregwarCaptchaBundle
gregwar_captcha_routing:
    resource: '@GregwarCaptchaBundle/Resources/config/routing/routing.yml'

# HWIOAuthBundle
hwi_oauth_routing:
    resource: 'routing/oauth.yml'
