
imports:
    - { resource: services/chebur.yml }
    - { resource: services/doctrine.yml }
    - { resource: services/guzzle.yml }
    - { resource: services/monolog.yml }
    - { resource: services/symfony.yml }
    - { resource: services/swiftmailer.yml }

parameters:
    # Twig cache bundle
    twig_cache.adapter.class: Asm89\Twig\CacheExtension\CacheProvider\PsrCacheAdapter

    # HWI OAuth Bundle
    hwi_oauth.security.oauth_utils.class: App\OAuth\OAuthUtils

services:

# Commands
    App\Command\:
        resource: '%kernel.source_dir%/Command'
        tags: ['console.command']

# Controllers (делаем через сервисы, чтобы работал автокомплит)
    App\Controller\:
        resource: '%kernel.source_dir%/Controller'

# Cache
    cache.default.simple: #psr16
        class: Symfony\Component\Cache\Simple\Psr6Cache
        arguments:
            - '@cache.default'

#Auth
    app.auth.log.subscriber:
        class: App\Auth\Log\AuthLogEventSubscriber
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@request_stack'
            - '@app.visitor.manager'
            - '@app.user_agent.manager'
        tags:
            - { name: kernel.event_subscriber }

    app.auth.log.helper:
        class: App\Auth\Log\AuthLogHelper

    app.auth.log.twig.extension:
        class: App\Twig\Extension\AuthLogExtension
        arguments:
            - '@app.auth.log.helper'
        tags:
            - { name: twig.extension }

    app.auth.user_checker:
        class: App\Auth\UserChecker

    app.auth.password_helper:
        class: App\Auth\PasswordHelper
        arguments:
            - '@security.encoder_factory'

    app.auth.login_manager:
        class: App\Auth\LoginManager
        arguments:
            - '@security.token_storage'
            - '@security.user_checker'
            - '@security.authentication.session_strategy'
            - '@request_stack'
            - '@event_dispatcher'
            - '@app.user.manager'

    fos_user.security.login_manager:
        alias: app.auth.login_manager

# User Providers
    app.auth.user_provider.main:
        class:  App\Auth\UserProvider\UserProviderMain
        public: false
        arguments:
            - '@app.user.manager'

    app.auth.user_provider.admin:
        class:  App\Auth\UserProvider\UserProviderAdmin
        public: false
        arguments:
            - '@app.user.manager'

# Auth Forms
    app.auth.form.type.registration:
        class: App\Auth\Form\Type\RegistrationFormType
        arguments:
            - '@app.user.manipulator'
        tags:
            - { name: form.type }

    app.auth.form.type.reset_request:
        class: App\Auth\Form\Type\ResetRequestFormType
        arguments:
            - '@app.user.manager'
            - '@app.user.token_manager'
            - '@app.mailer.tokened'
        tags:
            - { name: form.type }

    app.auth.form.type.reset_reset:
        class: App\Auth\Form\Type\ResetFormType
        arguments:
            - '@app.user.manipulator'
            - '@app.auth.login_manager'
        tags:
            - { name: form.type }

    app.auth.form.type.login.main:
        class: App\Auth\Form\Type\LoginMainFormType
        arguments:
            - '@router'
            - '@app.email.helper'
            - '@validator'
        tags:
            - { name: form.type }

    app.auth.form.type.login.admin:
        class: App\Auth\Form\Type\LoginAdminFormType
        parent: app.auth.form.type.login.main
        tags:
            - { name: form.type }

#OAuth
    app.oauth.user_provider.main:
        class: App\OAuth\UserProvider\UserProviderMain
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@app.oauth.resource_owner.helper'

    app.oauth.connector:
        class: App\OAuth\Connector
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@app.oauth.resource_owner.helper'

    app.oauth.resource_owner.helper:
        class: App\OAuth\ResourceOwnerHelper

    app.oauth.twig.extension:
        class: App\Twig\Extension\OAuthExtension
        arguments:
            - '@app.oauth.resource_owner.helper'
        tags:
            - { name: twig.extension }

# Email
    app.email.check_url_detector:
        class: App\Email\EmailCheckUrlDetector

    app.email.helper:
        class: App\Email\EmailHelper

    app.email.twig.extension:
        class: App\Twig\Extension\EmailExtension
        arguments:
            - '@app.email.helper'
            - '@app.email.check_url_detector'
        tags:
            - { name: twig.extension }


# Mailer
    app.mailer.mailer:
        class: App\Mailer\Mailer
        arguments:
            - '@swiftmailer.mailer'
            - '@templating'

    app.mailer.tokened:
        class: App\Mailer\MailerTokened
        arguments:
            - '@app.mailer.mailer'
            - '@router'
            - '@app.user.token_manager'


# Token
    app.token.generator:
        class: App\Token\TokenGenerator

    fos_user.util.token_generator:
        alias: app.token.generator


#Visitor
    app.visitor.manager:
        class: App\Visitor\VisitorManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@request_stack'

    app.visitor.listener:
        class: App\Visitor\Event\VisitorSubscriber
        arguments:
            - '@app.visitor.manager'
        tags:
            - { name: kernel.event_subscriber }


# User agent
    app.user_agent.manager:
        class: App\UserAgent\UserAgentManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@request_stack'

#Timezone
    app.timezone.manager:
        class: App\Timezone\TimezoneManager

    app.timezone.event_subscriber:
        class: App\Timezone\TimezoneEventSubscriber
        arguments:
            - '@app.user.manager'
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: kernel.event_subscriber }

# User
    app.user.manager:
        public: true
        class: App\User\UserManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.token_storage'
            - '@app.email.helper'

    fos_user.user_manager:
        alias: app.user.manager

    app.user.manipulator:
        class: App\User\UserManipulator
        arguments:
            - '@app.user.manager'
            - '@app.auth.password_helper'
            - '@app.mailer.tokened'
            - '@app.user.token_manager'

    app.user.token_manager:
        class: App\User\UserTokenManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@app.token.generator'

    app.user.security.voter:
        class: App\User\Security\UserVoter
        arguments:
            - '@security.access.decision_manager'
            - '@app.user.token_manager'
        tags:
            - { name: security.voter }

# User search
    app.user.search.admin:
        class: App\User\Search\UserSearchAdmin
        arguments:
            - '@doctrine.orm.entity_manager'

    app.user.search.form.type.admin:
        class: App\User\Search\Form\Type\SearchAdminFormType
        tags:
            - { name: form.type }

# User forms
    app.user.form.type.create:
        class: App\User\Form\Type\CreateUserFormType
        arguments:
            - '@app.user.manipulator'
        tags:
            - { name: form.type }

    app.user.form.type.edit:
        class: App\User\Form\Type\EditUserFormType
        arguments:
            - '@app.user.manager'
        tags:
            - { name: form.type }

    app.user.form.type.change_timezone:
        class: App\User\Form\Type\ChangeTimezoneFormType
        arguments:
            - '@app.user.manager'
            - '@app.timezone.manager'
        tags:
            - { name: form.type }

    app.user.form.type.change_password:
        class: App\User\Form\Type\ChangePasswordFormType
        arguments:
            - '@app.user.manager'
            - '@app.user.manipulator'
        tags:
            - { name: form.type }

    app.user.form.type.change_username:
        class: App\User\Form\Type\ChangeUsernameFormType
        arguments:
            - '@app.user.manager'
            - '@app.user.manipulator'
        tags:
            - { name: form.type }

    app.user.form.type.change_username_admin:
        class: App\User\Form\Type\ChangeUsernameAdminFormType
        arguments:
            - '@app.user.manipulator'
        tags:
            - { name: form.type }

    app.user.form.type.change_email:
        class: App\User\Form\Type\ChangeEmailFormType
        arguments:
            - '@app.user.manager'
            - '@app.mailer.tokened'
        tags:
            - { name: form.type }

    app.user.form.type.change_email_admin:
        class: App\User\Form\Type\ChangeEmailAdminFormType
        arguments:
            - '@app.user.manipulator'
        tags:
            - { name: form.type }

# User review
    app.user.review.manager:
        class: App\User\Review\UserReviewManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@app.user.manager'

    app.user.review.voter:
        class: App\User\Review\Security\UserReviewVoter
        arguments:
            - '@security.access.decision_manager'
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: security.voter }

    app.user.review.form.type.create:
        class: App\User\Review\Form\Type\UserReviewCreateFormType
        arguments:
            - '@app.user.review.manager'
        tags:
            - { name: form.type }

    app.user.review.search.source:
        class: App\User\Review\Search\UserReviewItemsSource
        arguments:
            - '@doctrine.orm.entity_manager'

    app.user.review.type.twig.extension:
        class: App\Twig\Extension\UserReviewExtension
        tags:
            - { name: twig.extension }

# Chat
    app.chat.manager:
        class: App\Chat\ChatManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@app.user.manager'

    app.chat.security.voter:
        class: App\Chat\Security\ChatVoter
        tags:
            - { name: security.voter }

    app.chat.counter:
        class: App\Chat\ChatCounter
        arguments:
            - '@doctrine.orm.entity_manager'

    app.chat.search.chats:
        class: App\Chat\Search\ChatsItemsSource
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@app.user.manager'
            - '@app.chat.search.transformer'

    app.chat.search.transformer:
        class: App\Chat\Search\ChatSearchItemTransformer
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@app.user.manager'
            - '@app.chat.message.search.transformer'

    app.chat.twig.extension:
        class: App\Twig\Extension\ChatExtension
        arguments:
            - '@app.chat.counter'
            - '@app.user.manager'
        tags:
            - { name: twig.extension }

# Char messages
    app.chat.message.form.type.create:
        class: App\Chat\Message\Form\Type\ChatMessageCreateFormType
        arguments:
            - '@app.chat.manager'
            - '@app.symfony.form.helper'
        tags:
            - { name: form.type }

    app.chat.message.search:
        class: App\Chat\Message\Search\ChatMessagesItemsSource
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@app.user.manager'
            - '@app.chat.message.search.transformer'

    app.chat.message.search.transformer:
        class: App\Chat\Message\Search\ChatMessageSearchItemTransformer
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@app.user.manager'
