
app_public:
    resource: 'routing/public.yml'

app_auth:
    resource: 'routing/auth.yml'

app_private:
    prefix:   /pa
    resource: 'routing/private.yml'

app_admin:
    prefix:   /admin
    resource: 'routing/admin.yml'