
imports:
    - { resource: services/symfony.yml }

services:

# Email
    app.email.check_url_detector:
        class: App\Email\EmailCheckUrlDetector

    app.email.helper:
        class: App\Email\EmailHelper

    app.email.twig.extension:
        class: AppBundle\Twig\Extension\EmailExtension
        arguments:
            - '@app.email.helper'
            - '@app.email.check_url_detector'
        tags:
            - { name: twig.extension }


# Token
    app.token.generator:
        class: App\Token\TokenGenerator

    fos_user.util.token_generator:
        alias: app.token.generator


#Visitor
    app.visitor.manager:
        class: App\Visitor\VisitorManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@request_stack'

    app.visitor.listener:
        class: App\Visitor\Event\VisitorSubscriber
        arguments:
            - '@app.visitor.manager'
        tags:
            - { name: kernel.event_subscriber }


# User
    app.user.manager:
        lazy:  true
        class: App\User\UserManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.token_storage'
            - '@app.email.helper'

    fos_user.user_manager:
        alias: app.user.manager

    app.user.token_manager:
        class: App\User\UserTokenManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@app.token.generator'
