
# prefix: /admin/user

app_admin_user__review_index:
    path:     /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: app_admin_user_review_list, permanent: true }

app_admin_user_review_list:
    path:     /list
    defaults: { _controller: App\Controller\Admin\UserReviewController:listAction }

app_admin_user_review_delete:
    path:     /{id}/delete
    methods:  ['POST']
    defaults: { _controller: App\Controller\Admin\UserReviewController:deleteAction }
    requirements:
        id: '\d+'
    options:
        expose: true
    #todo ajax only
